'use client';

import { useState, useEffect } from 'react';
import { Save, RotateCcw, FileText, AlertCircle, CheckCircle } from 'lucide-react';
import { seoAPI } from '@/lib/seo/api-client';

export function RobotsTxtEditor() {
  const [content, setContent] = useState('');
  const [originalContent, setOriginalContent] = useState('');
  const [notes, setNotes] = useState('');
  const [isLoading, setIsLoading] = useState(true);
  const [isSaving, setIsSaving] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [success, setSuccess] = useState(false);
  const [version, setVersion] = useState(1);
  const [hasChanges, setHasChanges] = useState(false);

  useEffect(() => {
    loadRobotsTxt();
  }, []);

  useEffect(() => {
    setHasChanges(content !== originalContent);
  }, [content, originalContent]);

  const loadRobotsTxt = async () => {
    try {
      setIsLoading(true);
      setError(null);
      const data = await seoAPI.getRobotsTxt();
      setContent(data.content);
      setOriginalContent(data.content);
      setVersion(data.version);
    } catch (err) {
      setError('Failed to load robots.txt');
      console.error(err);
    } finally {
      setIsLoading(false);
    }
  };

  const handleSave = async () => {
    try {
      setIsSaving(true);
      setError(null);
      setSuccess(false);

      const data = await seoAPI.updateRobotsTxt(content, notes);
      setOriginalContent(content);
      setVersion(data.version);
      setNotes('');
      setSuccess(true);

      setTimeout(() => setSuccess(false), 3000);
    } catch (err: any) {
      setError(err.message || 'Failed to save robots.txt');
      console.error(err);
    } finally {
      setIsSaving(false);
    }
  };

  const handleReset = () => {
    setContent(originalContent);
    setNotes('');
    setError(null);
    setSuccess(false);
  };

  const handleLoadDefault = () => {
    const defaultContent = `# Robots.txt for ChatGPT Philippines
# Generated by SEO Management System

User-agent: *
Allow: /

# Disallow admin and API routes
Disallow: /admin/
Disallow: /api/
Disallow: /api/auth/

# Disallow search and filter pages
Disallow: /*?*search=
Disallow: /*?*filter=

# Allow specific bots
User-agent: Googlebot
Allow: /

User-agent: Bingbot
Allow: /

# Sitemaps
Sitemap: ${process.env.NEXT_PUBLIC_SITE_URL || 'https://chatgpt-philippines.com'}/sitemap.xml
Sitemap: ${process.env.NEXT_PUBLIC_SITE_URL || 'https://chatgpt-philippines.com'}/sitemap-tools.xml
Sitemap: ${process.env.NEXT_PUBLIC_SITE_URL || 'https://chatgpt-philippines.com'}/sitemap-articles.xml`;

    setContent(defaultContent);
  };

  const validateRobotsTxt = () => {
    const warnings: string[] = [];

    if (!content.includes('User-agent:')) {
      warnings.push('Missing User-agent directive');
    }

    if (!content.includes('Sitemap:')) {
      warnings.push('No sitemap reference found');
    }

    if (content.includes('/admin') || content.includes('/api')) {
      // Good practice
    } else {
      warnings.push('Consider blocking /admin/ and /api/ routes');
    }

    return warnings;
  };

  const warnings = validateRobotsTxt();

  if (isLoading) {
    return (
      <div className="flex items-center justify-center h-64">
        <div className="animate-spin rounded-full h-8 w-8 border-b-2 border-orange-500"></div>
      </div>
    );
  }

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex items-center justify-between">
        <div className="flex items-center gap-3">
          <FileText className="w-6 h-6 text-orange-500" />
          <div>
            <h2 className="text-xl font-bold text-neutral-900">Robots.txt Editor</h2>
            <p className="text-sm text-neutral-600">Version {version}</p>
          </div>
        </div>
        <div className="flex items-center gap-2">
          <button
            onClick={handleLoadDefault}
            className="px-4 py-2 text-sm border border-neutral-300 rounded-lg hover:bg-neutral-50 transition-colors"
          >
            Load Default
          </button>
          {hasChanges && (
            <button
              onClick={handleReset}
              className="px-4 py-2 text-sm border border-neutral-300 rounded-lg hover:bg-neutral-50 transition-colors flex items-center gap-2"
            >
              <RotateCcw className="w-4 h-4" />
              Reset
            </button>
          )}
          <button
            onClick={handleSave}
            disabled={isSaving || !hasChanges}
            className="px-4 py-2 text-sm bg-orange-500 text-white rounded-lg hover:bg-orange-600 transition-colors disabled:opacity-50 disabled:cursor-not-allowed flex items-center gap-2"
          >
            <Save className="w-4 h-4" />
            {isSaving ? 'Saving...' : 'Save Changes'}
          </button>
        </div>
      </div>

      {/* Alerts */}
      {error && (
        <div className="p-4 bg-red-50 border border-red-200 rounded-lg flex items-start gap-3">
          <AlertCircle className="w-5 h-5 text-red-600 flex-shrink-0 mt-0.5" />
          <div>
            <p className="font-medium text-red-900">Error</p>
            <p className="text-sm text-red-700">{error}</p>
          </div>
        </div>
      )}

      {success && (
        <div className="p-4 bg-green-50 border border-green-200 rounded-lg flex items-start gap-3">
          <CheckCircle className="w-5 h-5 text-green-600 flex-shrink-0 mt-0.5" />
          <div>
            <p className="font-medium text-green-900">Success</p>
            <p className="text-sm text-green-700">Robots.txt updated successfully</p>
          </div>
        </div>
      )}

      {/* Warnings */}
      {warnings.length > 0 && (
        <div className="p-4 bg-yellow-50 border border-yellow-200 rounded-lg">
          <div className="flex items-start gap-3">
            <AlertCircle className="w-5 h-5 text-yellow-600 flex-shrink-0 mt-0.5" />
            <div className="flex-1">
              <p className="font-medium text-yellow-900 mb-2">Warnings</p>
              <ul className="space-y-1">
                {warnings.map((warning, index) => (
                  <li key={index} className="text-sm text-yellow-700">• {warning}</li>
                ))}
              </ul>
            </div>
          </div>
        </div>
      )}

      {/* Editor */}
      <div className="bg-white rounded-xl border border-neutral-200 overflow-hidden">
        <div className="bg-neutral-50 px-4 py-3 border-b border-neutral-200">
          <h3 className="font-medium text-neutral-900">Content</h3>
        </div>
        <div className="p-4">
          <textarea
            value={content}
            onChange={(e) => setContent(e.target.value)}
            rows={20}
            className="w-full px-4 py-3 font-mono text-sm bg-neutral-900 text-green-400 rounded-lg focus:outline-none focus:ring-2 focus:ring-orange-500 resize-none"
            placeholder="Enter robots.txt content..."
          />
          <div className="mt-2 text-sm text-neutral-600">
            {content.split('\n').length} lines • {content.length} characters
          </div>
        </div>
      </div>

      {/* Change Notes */}
      {hasChanges && (
        <div className="bg-white rounded-xl border border-neutral-200 overflow-hidden">
          <div className="bg-neutral-50 px-4 py-3 border-b border-neutral-200">
            <h3 className="font-medium text-neutral-900">Change Notes (Optional)</h3>
          </div>
          <div className="p-4">
            <textarea
              value={notes}
              onChange={(e) => setNotes(e.target.value)}
              rows={3}
              className="w-full px-4 py-2 border border-neutral-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-orange-500 resize-none"
              placeholder="Describe what changed and why..."
            />
          </div>
        </div>
      )}

      {/* Info */}
      <div className="bg-blue-50 border border-blue-200 rounded-lg p-4">
        <h4 className="font-medium text-blue-900 mb-2">About Robots.txt</h4>
        <ul className="space-y-1 text-sm text-blue-800">
          <li>• Controls which parts of your site search engines can access</li>
          <li>• Changes take effect immediately after saving</li>
          <li>• All versions are saved for reference and rollback</li>
          <li>• Test your robots.txt at Google Search Console</li>
        </ul>
      </div>
    </div>
  );
}
