/**
 * Dynamic Robots.txt Generator
 *
 * Publicly accessible at /robots.txt
 * Automatically serves active robots.txt from database
 */

import { NextRequest, NextResponse } from 'next/server';
import { createClient } from '@supabase/supabase-js';

const supabase = createClient(
  process.env.NEXT_PUBLIC_SUPABASE_URL!,
  process.env.SUPABASE_SERVICE_ROLE_KEY!
);

const SITE_URL = process.env.NEXT_PUBLIC_SITE_URL || 'https://chatgpt-philippines.com';

export async function GET(request: NextRequest) {
  try {
    // Fetch active robots.txt from database
    const { data, error } = await supabase
      .from('robots_config')
      .select('content')
      .eq('is_active', true)
      .order('created_at', { ascending: false })
      .limit(1)
      .single();

    if (error || !data) {
      console.error('Database error or no robots.txt found:', error);
      return new NextResponse(getDefaultRobotsTxt(), {
        headers: {
          'Content-Type': 'text/plain',
          'Cache-Control': 'public, max-age=3600, s-maxage=3600',
        },
      });
    }

    return new NextResponse(data.content, {
      headers: {
        'Content-Type': 'text/plain',
        'Cache-Control': 'public, max-age=3600, s-maxage=3600',
      },
    });
  } catch (error) {
    console.error('Unexpected error:', error);
    return new NextResponse(getDefaultRobotsTxt(), {
      headers: {
        'Content-Type': 'text/plain',
        'Cache-Control': 'public, max-age=3600, s-maxage=3600',
      },
    });
  }
}

function getDefaultRobotsTxt(): string {
  return `# Robots.txt for ChatGPT Philippines
# Generated by SEO Management System

User-agent: *
Allow: /

# Disallow admin and API routes
Disallow: /admin/
Disallow: /api/
Disallow: /api/auth/

# Disallow search and filter pages
Disallow: /*?*search=
Disallow: /*?*filter=

# Allow specific bots
User-agent: Googlebot
Allow: /

User-agent: Bingbot
Allow: /

# Sitemaps
Sitemap: ${SITE_URL}/sitemap.xml`;
}
